name: Test PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
    tests:
      runs-on: ubuntu-latest
      steps:
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                # Checkout the merge commit to include changes from both the base and the head of the PR
                ref: refs/pull/${{ github.event.pull_request.number }}/merge
                sparse-checkout: |
                    .github
                    build.rs
                    Cargo.lock
                    Cargo.toml
                    pyproject.toml
                    src
                    tests
                    uv.lock
                    README.md
                    LICENSE
            - name: Set up Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                components: clippy,rustfmt
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                # Uses the latest python version allowed by the project's constraints.
                python-version-file: pyproject.toml

            - name: Install uv
              uses: astral-sh/setup-uv@v8.1.0
              with:
              # Install a specific version of uv.
                version: '0.11.2'
                enable-cache: true
                cache-dependency-glob: |
                  **/uv.lock
                  **/pyproject.toml

            - name: Audit dependencies
              run: |
                uv audit --locked --preview-features audit

            - name: Install dev dependencies
              run: |
                uv sync --locked --all-groups

            - name: Run Rust and Python checks
              run: uv run src/scripts/ci_checks.sh
